services:
  apifirst-server-jpa:
    container_name: apifirst-server-jpa
    image: local/apifirst-server-jpa:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    expose:
      - 8081
    environment:
      SERVER_PORT: 8081
