spring:
  application:
    name: apifirst-server-jpa
  
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb-for-apifirst-server-jpa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: 
      driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # Show SQL  
        show_sql: true
        # Format SQL
        format_sql: true
  h2:
    console:
      enabled: false      
    
  docker:
    compose:
      enabled: false
      stop:
        command: down  
        
management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always     
        
logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      - path: /actuator/health        
